App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('instructor_login/', views.instructor_login, name='instructor_login'),
    path('learner_login/', views.learner_login, name='learner_login'),
    path('instructor_signup/', views.instructor_signup, name='instructor_signup'),
    path('learner_signup/', views.learner_signup, name='learner_signup'),
    path('logout/', views.logout_user, name='logout'),
    path('instructor_profile/', views.instructor_profile, name='instructor_profile'),
    path('learner_profile/', views.learner_profile, name='learner_profile'),
    path('edit_instructor/', views.edit_instructor, name='edit_instructor'),
    path('edit_learner/', views.edit_learner, name='edit_learner'),
]

ELearning_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Courses.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('courses/', include('App_Courses.urls')),
    path('', Home.as_view(), name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='instructor_profile')
    first_name = models.CharField(max_length=264, blank=True)
    last_name = models.CharField(max_length=264, blank=True)
    email = models.EmailField(blank=True)
    job_position = models.CharField(max_length=264, blank=True)
    subject = models.CharField(max_length=264, blank=True)

    def __str__(self):
        return self.user.username

class Learner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='learner_profile')
    first_name = models.CharField(max_length=264, blank=True)
    last_name = models.CharField(max_length=264, blank=True)
    email = models.EmailField(blank=True)
    institution = models.CharField(max_length=264, blank=True)

    def __str__(self):
        return self.user.username
    

App_Login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from App_Login.models import Instructor, Learner

class LoginForm(AuthenticationForm):
    username = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'username'}))
    password = forms.CharField(
        required=True,
        label = "",
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    class Meta:
        model = User
        fields = ('username', 'password')

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label="",widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(
        required=True,
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        required=True,
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder': 'Password Confirmation'})
    )
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class InstructorForm(forms.ModelForm):
    class Meta:
        model = Instructor
        exclude = ('user', )

class LearnerForm(forms.ModelForm):
    class Meta:
        model = Learner
        exclude = ('user', )

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from App_Login.models import Instructor, Learner
from App_Login.forms import LoginForm, SignUpForm, InstructorForm, LearnerForm

# Create your views here.

def homepage(request):
    return render(request, 'App_Login/homepage.html', context={})


def instructor_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Login:instructor_profile'))
    return render(request, 'App_Login/login.html', context={'instructor':True, 'form':form})

def learner_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('App_Login:learner_profile'))
    return render(request, 'App_Login/login.html', context={'form':form})


def instructor_signup(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            instructor_profile = Instructor(user=request.user)
            instructor_profile.save()
            return HttpResponseRedirect(reverse('App_Login:instructor_login'))
    return render(request, 'App_Login/signup.html', context={'instructor': True, 'form':form}) 

def learner_signup(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            learner_profile = Learner(user=request.user)
            learner_profile.save()
            return HttpResponseRedirect(reverse('App_Login:learner_login'))
    return render(request, 'App_Login/signup.html', context={'form':form}) 


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:homepage'))


@login_required
def instructor_profile(request):
    return render(request, 'App_Login/profile.html', context={'instructor': True})

@login_required
def learner_profile(request):
    return render(request, 'App_Login/profile.html', context={})



@login_required
def edit_instructor(request):
    current_user = Instructor.objects.get(user=request.user)
    form = InstructorForm(instance=current_user)
    if request.method == 'POST':
        form = InstructorForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = InstructorForm(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:instructor_profile'))
    return render(request, 'App_Login/edit_profile.html', context={'form': form})

@login_required
def edit_learner(request):
    current_user = Learner.objects.get(user=request.user)
    form = LearnerForm(instance=current_user)
    if request.method == 'POST':
        form = LearnerForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = LearnerForm(instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:learner_profile'))
    return render(request, 'App_Login/edit_profile.html', context={'form': form})
 

templates/App_Login/edit_profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Edit profile {% endblock %}
{% block css_block %}

{% endblock %}
{% block body_block %}

<div class='edit-profile'>
    <h5>Edit your profile</h5>
    <form method="POST" enctype="multipart/form-data">
      {{ form|crispy}}
      {% csrf_token %}
      <button type="submit" style="width:100%" class="btn btn-primary">Update</button>
    </form>
  </div>

{% endblock %}

templates/App_Login/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <title>Welcome to E-Learners</title>
</head>
<body style="font-family: Arial, Helvetica, sans-serif, Tahoma;">
    <div class="container p-5">
        <div class="row p-5">
            <h1 class="text-center">Welcome to E-Learners</h1> <br>
        </div>
        <div class="row p-5">
            <center>
                
                    <p class="text-center">Join as</p> <br>
                    <a href="{% url 'App_Login:instructor_login' %}" class="btn btn-info btn-md">Instructor</a> <br>
                    or <br>
                    <a href="{% url 'App_Login:learner_login' %}" class="btn btn-primary btn-md">Learner</a>
                
            </center>
        </div>
    </div>
</body>
</html>

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}

<style>
    .sign_up {
        width: 450px;
        border: 1px solid #cccc7c;
        padding: 40px;
    }

    .log_in {
        width: 450px;
        padding: 25px;
        border: 1px solid #cccc7c;
    }
</style>
{% endblock %}

{% block body_block %}
<center>
    <div class='sign_up'>
        {% if instructor %}
        <h4>Log in to your instructor account </h4>
        {% else %}
        <h4>Log in to your learner account </h4>
        {% endif %}
        <form method="POST">
            {{ form|crispy}}
            {% csrf_token %}
            <button type="submit" style="width:100%" class="btn btn-primary">Login</button>
        </form>
    </div>
    <div class="log_in my-3">
        <p>Don't have an account?
            {% if instructor %} 
            <a href="{% url 'App_Login:instructor_signup' %}">
            {% else %}
            <a href="{% url 'App_Login:learner_signup' %}">
            {% endif %}
            Sign up</a>
        </p>
    </div>
</center>

templates/App_Login/profile.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}

<h2 class="text-center">Welcome to E-Learners</h2>
<div class="row pt-5">
    <div class="col-sm-4">
        <img src="/static/default.png" width="250px" height="250px" class="rounded-circle" alt="default">
    </div>
    <div class="col-sm-8">
        <br>
        {% if instructor %}
        <h3 class="text-center">Instructor Profile</h3>
        <p>
            <p>Username: </p>@{{user.username}} <br>
            <p>Name: </p>{{user.instructor_profile.first_name}} {{user.instructor_profile.last_name}} <br>
            <p>Email address: </p>{{user.instructor_profile.email}} <br>
            <p>Subject: </p>{{user.instructor_profile.subject}} <br>
            <p class="text-muted">{{user.instructor_profile.job_position}}</p><br>
            <a href="{% url 'App_Login:edit_instructor' %}" class="btn btn-info btn-sm">Edit profile</a>&nbsp;
            <a href="{% url 'App_courses:publish' %}" class="btn btn-secondary btn-sm">Publish a course</a>
        </p>
        {% else %}
        <p>
            <p>Username: </p>@{{user.username}} <br>
            <p>Name: </p>{{user.learner_profile.first_name}} {{user.learner_profile.last_name}} <br>
            <p>Email address: </p>{{user.learner_profile.email}} <br>
            <p class="text-muted">{{user.learner_profile.institution}}</p><br>
            <a href="{% url 'App_Login:edit_learner' %}" class="btn btn-info btn-sm">Edit profile</a>
        </p>
        {% endif %}
    </div>
</div><hr>


{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}
{% block css_block %}
<style>
    .sign_up {
        width: 450px;
        border: 1px solid #cccc7c;
        padding: 40px;
    }

    .log_in {
        width: 450px;
        padding: 25px;
        border: 1px solid #cccc7c;
    }
</style>
{% endblock %}

{% block body_block %}
<center>
    <div class='sign_up'>
        {% if instructor %}
        <h4>Sign up for a instructor account</h4>
        {% else %}
        <h4>Sign up for a learner account</h4>
        {% endif %}
        <form method="POST">
            {{ form|crispy}}
            {% csrf_token %}
            <button type="submit" style="width:100%" class="btn btn-primary">Sign up</button>
        </form>
    </div>
    <div class="log_in my-3">
        <p>Have an account?
            {% if instructor %} 
            <a href="{% url 'App_Login:instructor_login' %}">
            {% else %}
            <a href="{% url 'App_Login:learner_login' %}">
            {% endif %}
            Login here</a>
        </p>
    </div>
</center>


{% endblock %}