App_Courses/urls.py
from django.urls import path
from App_Courses import views

app_name = 'App_Courses'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('publish/', views.PublishCourse.as_view(), name='publish'),
    path('course_description/', views.course_description, name='course_description'),
    path('my_courses/', views.MyCourses.as_view(), name='my_courses'),
    path('question/<pk>/', views.question, name='question'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
    path('instructor_login/', views.instructor_login, name='instructor_login'),
    path('learner_login/', views.learner_login, name='learner_login'),
    path('instructor_signup/', views.instructor_signup, name='instructor_signup'),
    path('learner_signup/', views.learner_signup, name='learner_signup'),
    path('logout/', views.logout_user, name='logout'),
    path('instructor_profile/', views.instructor_profile, name='instructor_profile'),
    path('learner_profile/', views.learner_profile, name='learner_profile'),
    path('edit_instructor/', views.edit_instructor, name='edit_instructor'),
    path('edit_learner/', views.edit_learner, name='edit_learner'),
]

ELearning_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Courses.views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('courses/', include('App_Courses.urls')),
    path('', Home.as_view(), name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <title>{% block title_block %} E-Learners {% endblock %}</title>
  {% block css_block %} 
  {% endblock %}
</head>
<body>
    <div class="container" style='padding-top:20px'>
        {% block body_block %} {% endblock %}
      </div>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title_block %} E-Learners {% endblock %}</title>
    {% block css_block %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'App_Courses:home' %}">E-Learners</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        @{{user.username}}
                    </a>
                    <div class="dropdown-menu">
                        {% if user.instructor_profile %}
                        <a class="dropdown-item" href="{% url 'App_Courses:my_courses' %}">My Courses</a>
                        <a class="dropdown-item" href="{% url 'App_Login:instructor_profile' %}">Your Profile</a>
                        {% else %}
                        <a class="dropdown-item" href="{% url 'App_Login:learner_profile' %}">Your Profile</a>
                        {% endif %}
                        <hr>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                    </div>
                </div>
            </ul>
        </div>
    </nav>

    <div class="container" style='padding-top:80px'>
        {% block body_block %} {% endblock %}
      </div>


</body>
</html>